### получить список ШК продуктов из корзины
GET http://localhost:8080/basket


### добавить 1ШК продукта в корзину
POST http://localhost:8080/basket
Content-Type: application/json

{
  "barcode": "1234"
}

### добавить 2ШК продукта в корзину
POST http://localhost:8080/basket
Content-Type: application/json

{
  "barcode": "4321"
}

